//export const API_URL = 'http://localhost:3006/api/v1'
//UAT
export const API_URL = 'http://farmme.in.th:3006/api/v1'
//export const IMAGE_URL = 'http://farmme.in.th:3006'

//PD
// export const API_URL = 'https://runex.co:3006/api/v1'
export const IMAGE_URL = 'https://runex.co:3006'

export const HEADER = { headers: { 'Content-Type': 'application/json' } }
export const PF = 'web'
export const GA_ID = 'G-LC572RKD9Z'

export const gaTracking = {
  PREVIEW_EVENT : 'PREVIEW_EVENT',
  START_REG_EVENT : 'START_REG_EVENT',
  END_REG_EVENT : 'END_REG_EVENT',
}

export const userConstants = {
  PROFILE_UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  PROFILE_UPDATE_FAILURE: 'PROFILE_UPDATE_FAILURE',

  ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
  ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
  ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE',

  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  ME_REQUEST: 'USERS_GET_REQUEST',
  ME_SUCCESS: 'USERS_GET_SUCCESS',
  ME_FAILURE: 'USERS_GET_FAILURE',

  LOGOUT: 'USERS_LOGOUT',
  SHOW_LOGIN: 'SHOW_LOGIN',
  CLOSE_LOGIN: 'CLOSE_LOGIN',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

}

export const eventConstants = {
  SELECT_ADDRESS_REQUEST: 'SELECT_ADDRESS_REQUEST',
  SELECT_TICKET_REQUEST: 'SELECT_TICKET_REQUEST',
  SELECT_PRODUCT_REQUEST: 'SELECT_PRODUCT_REQUEST',
  SELECT_EVENT_REQUEST: 'SELECT_EVENT_REQUEST',

  REG_EVENT_REQUEST: 'REG_EVENT_REQUEST',
  REG_EVENT_SUCCESS: 'REG_EVENT_SUCCESS',
  REG_EVENT_FAIL: 'REG_EVENT_FAIL',

  PAYMENT_UPLOAD_SLIP_REQUEST: 'PAYMENT_UPLOAD_SLIP_REQUEST',
  PAYMENT_UPLOAD_SLIP_SUCCESS: 'PAYMENT_UPLOAD_SLIP_SUCCESS',
  PAYMENT_UPLOAD_SLIP_FAIL: 'PAYMENT_UPLOAD_SLIP_FAIL',
}

export const alertConstants = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  CLEAR: 'ALERT_CLEAR',
  LOADING: 'ALERT_LOADING',
}

export const regStatusConstants = {
  PAYMENT_WAITING: 'PAYMENT_WAITING',
  PAYMENT_WAITING_APPROVE: 'PAYMENT_WAITING_APPROVE',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAIL: 'PAYMENT_FAIL',

  PAYMENT_TRANSFER: 'PAYMENT_TRANSFER',
  PAYMENT_CREDIT_CARD: 'PAYMENT_CREDIT_CARD',
  PAYMENT_QRCODE: 'PAYMENT_QRCODE',
}